import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Manager from '../components/Manager'
import * as os from 'os'
import { IndexProps } from '../types'

import path from 'path'

const Index: NextPage<IndexProps> = ({ separator, startDirectory }) => {
  return (
    <div>
      <Head>
        <title>Video Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Manager separator={separator} startDirectory={startDirectory} />
    </div>
  )
}

export default Index

export const getServerSideProps: GetServerSideProps = async (context: any) => {
  // console.log('proccess', process.cwd())
  return {
    props: {
      separator: os.type() === ('Darwin' || 'Linux') ? '/' : '\\',
      startDirectory: path.join(process.cwd(), 'file-manager'),
    },
  }
}
